# Numerical Python

In [6]:
import numpy as np

In [8]:
## change list to vector
a = np.array([1,2,3])

In [9]:
a*3

array([3, 6, 9])

# Math Functions

In [12]:
## sum
np.sum(a)

6

In [13]:
## average
np.mean(a)

2.0

In [14]:
## standard deviasi
np.std(a)

0.816496580927726

In [15]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

# arange, linspace, logspace

In [17]:
## create a vector with range 
np.arange(0,5,1.5)

array([0. , 1.5, 3. , 4.5])

In [19]:
## memecah 0-10 dalam 5 bagian
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
## logaritmik space 
np.logspace(-3,3,7)

array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

# Random

In [27]:
np.random.rand()

0.3483097318477082

In [31]:
## 3 coloumn
np.random.rand(3)

array([0.13444985, 0.76870258, 0.00859696])

In [32]:
## 3 column 2 row
np.random.rand(3,2)

array([[0.50616981, 0.98233339],
       [0.78812882, 0.07039044],
       [0.5725314 , 0.50172123]])

# Controlled Randomness

In [51]:
## static suffle / scientific 
## Reproduceble
state = np.random.RandomState(42)
state.rand(3)

array([0.37454012, 0.95071431, 0.73199394])